# === Telegram Settings ===
BOT_TOKEN = ""   # loaded dynamically from GitHub Actions secrets
CHAT_ID = ""     # loaded dynamically from GitHub Actions secrets

# === NIFTY 50 Stocks + GOLD + BITCOIN ===
NIFTY50_STOCKS = [
    "RELIANCE.NS", "HDFCBANK.NS", "BHARTIARTL.NS", "TCS.NS", "ICICIBANK.NS",
    "INFY.NS", "KOTAKBANK.NS", "LT.NS", "AXISBANK.NS", "HINDUNILVR.NS",
    "ITC.NS", "SBIN.NS", "BAJFINANCE.NS", "HCLTECH.NS", "ASIANPAINT.NS",
    "WIPRO.NS", "MARUTI.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "TITAN.NS",
    "BPCL.NS", "SUNPHARMA.NS", "GRASIM.NS", "JSWSTEEL.NS", "DIVISLAB.NS",
    "ADANIPORTS.NS", "M&M.NS", "POWERGRID.NS", "ONGC.NS", "COALINDIA.NS",
    "DRREDDY.NS", "NTPC.NS", "HEROMOTOCO.NS", "TATASTEEL.NS", "BAJAJ-AUTO.NS",
    "BAJAJFINSV.NS", "UPL.NS", "TECHM.NS", "HDFCLIFE.NS", "SBILIFE.NS",
    "ADANIENT.NS", "DMART.NS", "INDUSINDBK.NS", "AMBUJACEM.NS", "ADANIGREEN.NS",
    "JSWENERGY.NS", "CHOLAFIN.NS", "SIEMENS.NS", "HAVELLS.NS", "ICICIGI.NS",
    "PNB.NS", "BAJAJHLDNG.NS", "CANBK.NS", "TATACOMM.NS", "PIDILITIND.NS",
    "GODREJCP.NS", "SHREECEM.NS", "BANKBARODA.NS", "INDIGO.NS", "EICHERMOT.NS",
    "ABB.NS", "VEDL.NS", "TATAPOWER.NS", "BEL.NS", "BANKINDIA.NS",
    "IDFCFIRSTB.NS", "GAIL.NS", "BOSCHLTD.NS", "NAUKRI.NS", "TORNTPHARM.NS",
    "SOLARINDS.NS", "IRFC.NS", "MAZDOCK.NS", "ZYDUSLIFE.NS", "PFC.NS",
    "GRANULES.NS", "BALKRISIND.NS", "TRENT.NS", "TVSMOTOR.NS", "IDBI.NS",
    "HINDZINC.NS"
]
